### ISSUE TITLE
23 January 2019

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/LinuxCrashCourse#1]
Attendance

**Comment by dbc2201** [comment]
Divyansh Bhardwaj - 151500123 - Section 4H

**Comment by charus120** [comment]
Charu Singh-151500170-Section C1

**Comment by ankit998** [comment]
Ankit Agrawal -151500093 -section C1

**Comment by charus120** [comment]
Anshul Goyal 151500105 Section 4D

**Comment by l4zy0n3** [comment]
Yash Tripathi 151500642 Section B3

**Comment by littlepriyank** [comment]
Priyank Agarwal - 151500374 - Section 4B

**Comment by amansoni11397** [comment]
Aman soni-151500074-sec E1

**Comment by abhishek19988** [comment]
Abhishek Agarwal 151500014.      4C

**Comment by charus120** [comment]
Apurva Srivastava 151500123 Section 4C

**Comment by priyambansal13** [comment]
Priyam bansal 151500372 section 4B

**Comment by akashsaxena651** [comment]
Akash Saxena 151500047 section 3D

**Comment by VIJAYSVE** [comment]
Vijay Singh Verma. 151500601 Sec:- 4D

**Comment by amansoni11397** [comment]
Himanshu prakash-sec E 1515000233

**Comment by bishal86** [comment]
Bishal Gupta -151500167-Section A(42)

**Comment by ut00karsh** [comment]
Utkarsh shukla-151500589-section c

**Comment by harshisingh** [comment]
Harshita Singh - 151500225- section 4C

**Comment by Archita21** [comment]
Archita Asthana 151500126 4E

**Comment by devesh05** [comment]
Devesh kumar madnawat 151500188 4A

**Comment by amansoni11397** [comment]
Mayank agarwal- 151200213

**Comment by harshisingh** [comment]
Harshita Rastogi-151500224-4C

**Comment by akjain6750** [comment]
Akshat jain 151500052 sec 4A
Aditya chauhan 151500030 sec 4a
Shubham sharma 151500526 sec 4c

**Comment by akashsaxena651** [comment]
gaurav singh 151500206 section 21C

**Comment by VIJAYSVE** [comment]
Neelansh Kumar 151500314 Sec :-4D

**Comment by amansoni11397** [comment]
Aman mittal- 151500065F

**Comment by harshisingh** [comment]
Nimesh Srivastava-151500326-4C

**Comment by Akshatsrivastava700** [comment]
Akshat Srivastava-151500053-Sec-4A

**Comment by shukl08vk** [comment]
Vishnu Kant Shukla -151500621-4C

**Comment by purnimavar** [comment]
Purnima Varshney -151500379-C3

**Comment by piyushupa** [comment]
Piyush Kumar Upadhyay - 151500339 - 4D

**Comment by amansoni11397** [comment]
Kishan upadhayay-151200185E

**Comment by charus120** [comment]
Mayank Goyal 151500285 Section 4C

**Comment by hispy3** [comment]
Jitendra kumar 151500244 4D

**Comment by shivamg1212** [comment]
Shivam Gupta - 151500487 -4E

**Comment by charus120** [comment]
Mayank Goyal 151500285 Section 4C

**Comment by purnimavar** [comment]
Ankita Upadhyay-151500097-A1

**Comment by VIJAYSVE** [comment]
Adarsh Mishra 151500026 Sec- 4F

**Comment by 0110smriti** [comment]
Smriti Chaturvedi 151500537 sec 4B

**Comment by shikhashrma** [comment]
Shikha Sharma 151500476 secB

**Comment by harshjadaun** [comment]
Harsh kumar Jadaun-151500216-section 4A

**Comment by purnimavar** [comment]
Parul Varshney-151500336-C2

**Comment by akashsaxena651** [comment]
Divyanshu Singh 151500195.  section 4C(18)

**Comment by noahvishu** [comment]
Vishwender Singh 151500626 sec 4B

**Comment by shikhashrma** [comment]
Shikha Sharma 151500476 secB

**Comment by imran-shah-96** [comment]
Imran Ali Shah - 151500235 - 4E

**Comment by akshjyoti9** [comment]
Jyoti Goswami 151500245 section A 59 roll no

**Comment by ruchitom** [comment]
Ruchi tomar-151500430-4D

**Comment by sonaliagr** [comment]
Sonali Agrawal-151500540

**Comment by harshjadaun** [comment]
Vatsal tewari- 151500599-section 4B

**Comment by akashsaxena651** [comment]
Aditya Srivastava. 151500035. Section- 4F(07)

**Comment by purnimavar** [comment]
Km Shakshi Jain 151500262 C2

**Comment by Pranav289** [comment]
Pranav Jain 151500354 section - 4D

**Comment by vankit887** [comment]
Ankit Verma-151500095-Section-4F

**Comment by tanyaaaa** [comment]
Tanya tomar 151500578- 4D

**Comment by tANUJsHARMA8** [comment]
Tanuj Sharma 151500574 sec 4d

**Comment by 05aashijain** [comment]
Aashi 151500003 section-4D

**Comment by akshjyoti9** [comment]
Gaurav verma 161599002 section 4E

**Comment by purnimavar** [comment]
Devesh Vats 151500189 D1

**Comment by nikhil-web** [comment]
Nikhil Pandey -151500322 - 4A 
Ekansh Gupta - 151500197 -4A
Himanshu Kumar Agrawal -151500231 - 4A
Reema Gupta - 151500407 - 4E

**Comment by ruchitom** [comment]
Neelima Pandey-151500316-4D

**Comment by Pranav289** [comment]
Sakshi Gupta 151500440 section 4B

**Comment by sonaliagr** [comment]
Sonali Agrawal 151500540 4D

**Comment by charus120** [comment]
Mayank Goyal 151500285 Section 4C

**Comment by 05aashijain** [comment]
Shivani Agrawal 151500506 section-4B

**Comment by tanyaaaa** [comment]
Megha Sharma -151500289- 4D

**Comment by yams-1997** [comment]
Yamini Bajpai 151500633 4D

**Comment by akshjyoti9** [comment]
Sanni kumar 161599003 section 4E

**Comment by Pranav289** [comment]
Mansi Rawat 151500284 section 4D

**Comment by garimachaudhry** [comment]
Garima chaudhary 151500202 4C

**Comment by sonaliagr** [comment]
Surya Pratap Bhargav 151500558- 4F

**Comment by akshjyoti9** [comment]
Gopal 151500208 4F

**Comment by charus120** [comment]
Prakhar Mishra-151500353-Section 4C

**Comment by 05aashijain** [comment]
Shivani Agrawal 151500505 section 4D

**Comment by purnimavar** [comment]
Mohammed Sarfraz  151500294 Section C 33

**Comment by akshjyoti9** [comment]
Anuj gupta 151500112 4E

**Comment by sonaliagr** [comment]
Muskan Goyal 151500307- 4C

**Comment by charus120** [comment]
Nimisha Pundhir-151500329-A3

**Comment by akshjyoti9** [comment]
Aashi sharma(01)  151500004 secA
Romit chand verma (23)  151500428 sec B
Umang agrawal (62)  151500584 sec B

**Comment by Nkromin** [comment]
Neeraj Roy - 151500317 - Section 4C

**Comment by purnimavar** [comment]
Shubham Ratani 151500525 D3

**Comment by charus120** [comment]
Adya Mehra-151500036-A1

**Comment by Nkromin** [comment]
Dushyant Singh Bundela - 151500196 - 4D

**Comment by Tanya625** [comment]
Tanya Agarwal -151500576 -Section -C3

**Comment by bates2525** [comment]
Piyush Sharma-151500341-Section-A

**Comment by charus120** [comment]
Arnesh Maurya-151500129-A

**Comment by akshjyoti9** [comment]
Ekansh gupta 151500198 section 4E

**Comment by ssarikarajput** [comment]
Sarika singh 
151500450
Section 4B

**Comment by immayu** [comment]
Mayank singh-151500286-section 4D

**Comment by Tanya625** [comment]
Kant Agrawal -151500247-Section-C3

**Comment by mohitgupta3** [comment]
Mohit Gupta - 151500299 - Section - 4G

**Comment by pragatipriya25** [comment]
Pragati Priya- 151500348 - Section 4B

**Comment by devesh05** [comment]
Anushka singhai  151500122  4c

**Comment by DRAGONKINGEMPEROR** [comment]
Abhishek Gautam - 151500017 - Section 4A

**Comment by adityapranavcs** [comment]
Aditya Pranav -151500034 - Section 4A

**Comment by HarshitKhare** [comment]
Harshit Khare 151500221 Section 4A

**Comment by hhkk1997** [comment]
Hitesh Khandelwal 151500234 section 4E

**Comment by sonaliagr** [comment]
Romika Gupta 151500427- 4D

**Comment by sonaliagr** [comment]
Nikita Chauhan 151500324- 4E

**Comment by anurag12345678** [comment]
Anurag Singh 151500121 section 4E

**Comment by charus120** [comment]
Krishna Bansal-151500269-C

**Comment by sonaliagr** [comment]
Bhawna chaudhary 151500164-4E

**Comment by HarshitKhare** [comment]
Anuj Singh 151500114 Section 4A

**Comment by shikhashrma** [comment]
Simran Gupta 151500535 sec B

**Comment by shikhashrma** [comment]
Muskan Garg 151500305 sec E

**Comment by sharmabhupendra** [comment]
Bhupendra Sharma-151500166 -4C

**Comment by shaifaligupta1** [comment]
Shaifali Gupta - 151500468 - Section 4F

**Comment by Yash2309** [comment]
Yash Agarwal - 151500636  Sec - C

**Comment by ektagupta07** [comment]
151500199
Ekta Gupta
section A

**Comment by Namrata-Patel1** [comment]
Namrata Patel -151500310-section 4C

**Comment by Pratikasaxena** [comment]
Pratika Saxena - 151500365 -section 4F

**Comment by ektagupta07** [comment]
151500236
section D
isha gupta

**Comment by ArunKumarSingh2019** [comment]
Arun kumar singh - 151500133 section 4D

**Comment by tanyaaaa** [comment]
Saloni srivastava - 151500441- 4C
Nidhi pandey - 151500260- 4F

**Comment by Amritansh1997** [comment]
Amritansh Rai 151200059 - 4A

**Comment by shiv2060** [comment]
Shivam agrawal - 151500482 - section 4B

**Comment by muskangarg123** [comment]
Muskan garg-151500306-34D

**Comment by muskangarg123** [comment]
Prajjwal sharma-151500349-42D

**Comment by Namrata-Patel1** [comment]
Ayushi malik-151500157-4E

**Comment by saifahmedsid** [comment]
Saif Ahmed Siddiqui 151500438 -4B

**Comment by akashsaxena651** [comment]
hardik chatwal 151500214 Section-4f

**Comment by sahil135** [comment]
Sahil garg-151500437 4C

**Comment by ruchitom** [comment]
Alka Kumari 151500057. Sec-E

**Comment by sandeepsingh267** [comment]
Sandeep singh-151500446-4D

**Comment by saifahmedsid** [comment]
Avantika Dubey -151500148- Section 4A

**Comment by rohit-goswami** [comment]
Sagar Agrwal 151500434 Sec:4D

**Comment by ruchitom** [comment]
Shachi Jain 151500261 D
Sonali Jain 151500264 E
Alka Pundir 151500058 E

**Comment by ishanigohan** [comment]
yash sharma section 4E 151500640
gopal sharma section 4D 151500210

**Comment by shivang00001** [comment]
Shivang Mishra
4B
151500500

**Comment by antaramishra** [comment]
Antara Mishra - 151500107- Section 4A

**Comment by deepansh97** [comment]
Deepansh Kulshrestha-151500178- section 4A

**Comment by shivamdwivedi586** [comment]
shivam dwivedi-151500485-section-4E

**Comment by PriyaDwivedi123** [comment]
Priya Dwivedi-151500369-section-4D

**Comment by PriyaDwivedi123** [comment]
Kirtika Singh-151500257-section-4D

**Comment by deepansh97** [comment]
Mohd Aamir- 151500178- 4A

**Comment by muskangarg123** [comment]
Muskan garg-151500306-34C

**Comment by muskangarg123** [comment]
Prajjwal sharma-151500349-42C

**Comment by muskangarg123** [comment]
Vivek parashar-151500629-64C

**Comment by Arjit0chaurasia** [comment]
Arjit chaurasia- 151500127- 4A

**Comment by akshjyoti9** [comment]
Anuj saraswat 151500115 sec A
Manish gaur 151500278 sec A
Deepak singh 141500136 sec A

**Comment by akshjyoti9** [comment]
Anuj saraswat 151500115 sec A
Manish gaur 151500278 sec A
Deepak singh 141500136 sec A

**Comment by deepak2t896** [comment]
Ayush Kr Singh 151500154 sec A
Devansh Varshney 151500185 sec A

**Comment by AyushJain043** [comment]
Ayush Jain 151500153 Section A
Akash Kumar Ojha 151500045 Section A
Kshitij Bansal 151500270 Section A
Shivam Agrawal 151500483 Section D
Ayushi 151500155 Section D

**Comment by Arjit0chaurasia** [comment]
Rahul saraswat - 151500393 4B

**Comment by saifahmedsid** [comment]
Shivam Saxena -151500491-4F

**Comment by vk18mishra** [comment]
Vivek Mishra-151500628-4D

**Comment by PriyaDwivedi123** [comment]
Shreya Mishra-151500513-section-4B

**Comment by rshbhsngh62041** [comment]
Rishabh Singh- 151500417 - Section- 4D

**Comment by beingash22** [comment]
Ashutosh Tripathi
4C
151500145

**Comment by salonisri** [comment]
Saloni srivastava
Section c 
Roll no 53 
151500441

**Comment by shikhadwivedi12** [comment]
Shikha dwivedi sec c roll no 55 
151500475

**Comment by imran-shah-96** [comment]
Imran Ali Shah - 151500235 - 4E

**Comment by garimachaudhry** [comment]
Garima chaudhary 151500202 4C

**Comment by muskangarg123** [comment]
Muskan garg-151500306-34C

**Comment by Nidhipa** [comment]
Nidhi pandey
Sec_ F
151500260

**Comment by avantika1997** [comment]
Avantika Dubey
Sec A
151500148

**Comment by vankit887** [comment]
Ankit Verma
Sec 4F
151500095
