### ISSUE TITLE
Day 1 : 24 January 2019 - Linux Basics

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/LinuxCrashCourse#11]
Divyansh Bhardwaj - 151500123 - Section 4H

**Comment by charus120** [comment]
Charu Singh-151500170-Section 4C

**Comment by priyambansal13** [comment]
Priyam bansal - 151500372- section 4B

**Comment by dbc2201** [comment]
Achyut Upadhyay - 151500025 - Section 4B

**Comment by Akshatsrivastava700** [comment]
Akshat Srivastava-151500053-Section-4A

**Comment by adityapranavcs** [comment]
Aditya Pranav - 151500034- Section 4A

**Comment by ankit998** [comment]
Ankit Agrawal- 151500093 -Section 1C

**Comment by charus120** [comment]
Mimisha Mittal-151500292-Section 4A

**Comment by msarfrazanwar** [comment]
Mohammed Sarfraz Anwar 151500294 Section C2

**Comment by charus120** [comment]
Shubham Ratani-151500525-Section 4D

**Comment by ut00karsh** [comment]
Utkarsh shukla - 151500589 section 4c

**Comment by charus120** [comment]
Parul Varshney-151500336-Section 4C

**Comment by amansoni11397** [comment]
Aman soni -151500074- 4E

**Comment by bates2525** [comment]
Piyush Sharma-151500341-Section 4A

**Comment by noahvishu** [comment]
Vishwender Singh 151500626 section 4B

**Comment by 05aashijain** [comment]
Aashi - 151500003 - 4D

**Comment by VIJAYSVE** [comment]
Vijay Singh Verma 151500601 4D

**Comment by Tanya625** [comment]
Tanya Agarwal- 151500576-Section-4C

**Comment by 81shivani** [comment]
Shivani agrawal -151500506- section 4B

**Comment by shikhadwivedi12** [comment]
Shikha dwivedi-151500475-section-4C

**Comment by hispy3** [comment]
Jitendra kumar - 151500244- secrtion 4D

**Comment by shivamdwivedi586** [comment]
Shivam Dwivedi-151500485-section-4E

**Comment by vikasb011** [comment]
vikash badhautiya-151500606-sec E

**Comment by DRAGONKINGEMPEROR** [comment]
Abhishek Gautam - 151500017 - Section 4A

**Comment by ssarikarajput** [comment]
Sarika Singh 
151500450
Section 4B

**Comment by l4zy0n3** [comment]
Yash Tripathi - 151500642 - Section 4B

**Comment by 05aashijain** [comment]
Aashi - 151500003 - Section 4D

**Comment by Anubhav-Yadav** [comment]
Anubhav - 151500108 - Section 4C

**Comment by ekansh22** [comment]
Ekansh Gupta-151500197-4A

**Comment by Tanya625** [comment]
Kant Agrawal - 151500247 - Section 4C

**Comment by ankitau711** [comment]
Ankita Upadhyay - 151500097- Section 4A

**Comment by charus120** [comment]
Km Shakshi Jain - 151500262 - Section 2C

**Comment by Pranav289** [comment]
Pranav Jain - 151500354 - section-4D

**Comment by littlepriyank** [comment]
Priyank Agarwal - 151500374 - section 4B

**Comment by ghost** [comment]
Ekansh Gupta -151500198 - 4Yr. 
Section-E1

**Comment by adyamehra1** [comment]
Adya Mehra -151500036 - Section 4A

**Comment by pragatipriya25** [comment]
Pragati Priya - 151500348 -Section 4B

**Comment by Amritansh1997** [comment]
Amritansh Rai -151200059- Section -4A

**Comment by ankitau711** [comment]
Sakshi Gupta - 151500440- Section 4B

**Comment by ApurvaSrivastava** [comment]
Apurva Srivastava -151500123 - Section 4A

**Comment by charus120** [comment]
Devesh Vats - 151500189 - Section 1D

**Comment by deepansh97** [comment]
Deepansh Kulshrestha-151500178- section 4A

**Comment by harshjadaun** [comment]
Harsh Kumar Jadaun - 151500216 - Section 4A

**Comment by Bladewalker007** [comment]
Himanshu Kumar Agrawal - 151500231 - 4A

**Comment by purnimavar** [comment]
Purnima varshney - 151500379 - section 4C

**Comment by ApurvaSrivastava** [comment]
Anshul Goyal - 151500105 - Section 4D

**Comment by Nidhipa** [comment]
Nidhi pandey_151500260_sec 4f

**Comment by shukl08vk** [comment]
Vishnu Kant Shukla - 151500621-4C

**Comment by 0110smriti** [comment]
Smriti Chaturvedi - 151500537 - 4B

**Comment by HarshitKhare** [comment]
Harshit Khare - 151500221 - Section 4A

**Comment by purnimavar** [comment]
Surya prakash singh -151500557 - section 4b

**Comment by shaifaligupta1** [comment]
Shaifali Gupta - 151500468 - Section 4F

**Comment by Romitrcv** [comment]
Romit Chand Verma -  151500428 -  4B

**Comment by shikhashrma** [comment]
Shikha Sharma 
151500476
Sec 4B

**Comment by MohitLucifar** [comment]
Mohit Gupta
151500299
Section: 4G

**Comment by ArneshMaurya** [comment]
Arnesh Maurya - 151500129 - 4A

**Comment by adyamehra1** [comment]
Arnesh Maurya -151500129 - Section 4A

**Comment by avantika1997** [comment]
Avantika Dubey
Sec 4A
151500148

**Comment by saifahmedsid** [comment]
Saif Ahmed Siddiqui
4B
151500438

**Comment by hellothisisayush** [comment]
Ayush agarwal-151500149-section4a

**Comment by amanmajesty** [comment]
Aman Mishra -151500064-sec-4A

**Comment by MrLassagna** [comment]
Mohit Gupta
155100299
Section 4G

**Comment by ypsc01** [comment]
Yash Pratap Singh 151500639 section B3

**Comment by nimishagrawal18** [comment]
Nimish Agrawal - 151500327 -Section 4B

**Comment by devesh05** [comment]
Devesh kumar madnawat 151500188 4A

**Comment by antaramishra** [comment]
Antara Mishra
151500107
Section: 4A

**Comment by adyamehra1** [comment]
Nimisha Pundhir -151500329 - Section 4A

**Comment by devanshgaur25** [comment]
Devansh Gaur - 151500184 - section 4A

**Comment by tANUJsHARMA8** [comment]
Tanuj Sharma-151500574-Section 4D

**Comment by devesh05** [comment]
Anushka singhai 151500122 4C

**Comment by shipalisingh** [comment]
Shivanjali Gupta B-47
151500508

**Comment by HarshitKhare** [comment]
Namrata Patel - 151500310 - Section 4C

**Comment by BhadoriyaAjeet** [comment]
Ajeet Singh Bhadoriya-151500038-Section 4A

**Comment by shikhashrma** [comment]
Shikha Sharma -151500476-sec B

**Comment by anubbjhav** [comment]
Anubhav varshney-151500109-section4a

**Comment by mohdaamir15** [comment]
Mohd Aamir 151500295 Section 4A

**Comment by shipalisingh** [comment]
Anamika Singh 151500087 A-22
Sagar Agrwal 151500434  D-49

**Comment by akkii0001** [comment]
Akshay Chauhan - 151500055 - Section 4C

**Comment by harsh9935** [comment]
Harsh Mishra - 151500217 - Section 4E

**Comment by mayank-2010** [comment]
Mayank Goyal - 151500285 - sec 4C

**Comment by ishanigohan** [comment]
Isha Gupta -151500236 -Section 4D

**Comment by shiv2060** [comment]
Shivam Agrawal - 151500482 - section 4B

**Comment by aashi1111** [comment]
Aashi Sharma 
151500004
Section 4A

**Comment by AnshulGoyal04** [comment]
Krishna Bansal - 151500269 - Section 4C

**Comment by thebluntcoder** [comment]
Uttkarsh Mishra - 151500591 - Section 4B

**Comment by gauravvs** [comment]
Gaurav verma 161599002 section 4E

**Comment by neelanshkumar** [comment]
Neelansh Kumar 151500314 Sec- 4D

**Comment by tinkerbellpan** [comment]
Yash Sharma -151500640 -Section 4F

**Comment by shubham701** [comment]
Shubham Kumar Yadav - 151500523 - Section 4E

**Comment by tinkerbellpan** [comment]
Gopal Sharma -151500210 -Section 4D

**Comment by orthodox97** [comment]
Pratyush Shukla - 151500367 - Section 4B

**Comment by immayu** [comment]
Mayank singh- 151500286- section 4D

**Comment by vaibhavsolanki9761** [comment]
Vaibhav Solanki - 151500595 - 4B

**Comment by shivam4tech** [comment]
Shivam Shukla - 151500494 - Section 4B

**Comment by skdilipyadav** [comment]
Dilip Yadav - 151500190 - Section 4F

**Comment by mehuljain123** [comment]
Mehul Jain - 151500290 - Section 4F

**Comment by flash958** [comment]
Shivam Saxena - 151500492 - Section -4B

**Comment by thshubhamtomar** [comment]
Shubham Tomar 151500529 4E

**Comment by PriyaDwivedi123** [comment]
Priya Dwivedi-151500369-4D

**Comment by rahulBNM** [comment]
RAHUL KUMAR KESHRI   - 151500391   - section  4f

**Comment by PriyaDwivedi123** [comment]
Shreya Mishra-151500513-4B

**Comment by PriyaDwivedi123** [comment]
Antara Mishra-151500107-4A

**Comment by dushyant55** [comment]
Dushyant Singh Bundela-151500196-4D

**Comment by gulshan999** [comment]
Gulshan Kumar-151500213-Section 4D

**Comment by gulshan999** [comment]
Vaibhav Solanki-151500595-4B

**Comment by anuragvasu1** [comment]
Anurag Dwivedi - 151500117 - Section 4D

**Comment by sarthakkatiyar** [comment]
Sarthak Katiyar - 151500451 - Section 4E

**Comment by usumesh123** [comment]
Umesh Sharma - 151500585 - Section 4F

**Comment by shubham1097** [comment]
Shubham Agarwal - 151500516 - Section 4F

**Comment by Rahul-Gupt** [comment]
Rahul Gupta -151500386 - Section 4E

**Comment by ektagupta07** [comment]
Ekta Gupta - 151500199 - Section 4A

**Comment by snujs** [comment]
Anuj Gupta - 151500112 - Section 4E

**Comment by snujs** [comment]
Govind Upadhyay - 151500211 - Section 4E

**Comment by k178412** [comment]
Tarun Kumar - 151500580 - Section 4B

**Comment by AtomicTune** [comment]
Anurag Shakya - 151500119 - Section 4E

**Comment by sandeepsingh267** [comment]
Sandeep Singh -151500446-section 4D

**Comment by vikusin12** [comment]
vikas singh -161599006 - section 4F

**Comment by Rahulaggarwaal** [comment]
Rahul agarwal- 151500384- section 4c

**Comment by beingash22** [comment]
Ashutosh Tripathi- 151500145- section 4C

**Comment by muskangarg123** [comment]
Muskan garg-151500306-34C

**Comment by garimachaudhry** [comment]
Garima chaudhary 151500202 4C

**Comment by rshbhsngh62041** [comment]
Rishabh Singh - 151500417 - Section 4D

**Comment by BhadoriyaAjeet** [comment]
Sarvagya Shukla-151500452-4F

**Comment by Sbhangupta** [comment]
surajbhan-151500552 section-4F

**Comment by charus120** [comment]
Archita Asthana-151500126- Section 4E

**Comment by anurag12345678** [comment]
Anurag Singh 151500121 section 4E

**Comment by piyushupa** [comment]
Piyush Kumar Upadhyay 151500339 section 4D

**Comment by ArunKumarSingh2019** [comment]
Arun kumar singh 151500133 section 4D

**Comment by ypsc01** [comment]
Yash Pratap Singh 151500639 B3
