### ISSUE TITLE
Day 2 : 25 January 2019 - Permissions, Files & Folders

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/LinuxCrashCourse#18]
Divyansh Bhardwaj - 151500123 - Section 4H

**Comment by charus120** [comment]
Charu Singh-151500170-Section 4C

**Comment by msarfrazanwar** [comment]
Mohammed Sarfraz - 151500294 - Section 4C

**Comment by singhcharu1st** [comment]
Shubham Ratani-151500525-Section 4D

**Comment by parul1805** [comment]
Parul Varshney- 151500336-Section 4C

**Comment by priyambansal13** [comment]
Priyam Bansal - 151500372 - Section 4B

**Comment by Pranav289** [comment]
Pranav Jain - 151500354 - Section - 4D

**Comment by ghost** [comment]
Ekansh Gupta - 151500198 - Sec- 4E

**Comment by 81shivani** [comment]
Shivani agrawal- 151500506-Section 4B

**Comment by harsh9935** [comment]
Harsh Mishra - 151500217 - Section 4E

**Comment by shaifaligupta1** [comment]
Shaifali Gupta - 151500468 - Section 4F

**Comment by amansoni11397** [comment]
Aman soni 151500074-4E

**Comment by 0110smriti** [comment]
Smriti Chaturvedi - 151500537 -4B

**Comment by ankitau711** [comment]
Ankita Upadhyay - 151500097 - Section 4A

**Comment by BhadoriyaAjeet** [comment]
Ajeet Singh Bhadoriya-151500038-Section 4A

**Comment by harshjadaun** [comment]
Harsh Kumar Jadaun - 151500216 - section 4A

**Comment by Amritansh1997** [comment]
Amritansh Rai -151200059 - Section 4A

**Comment by Saurabh1065** [comment]
Saurabh Singh 151500463 Section B

**Comment by ApurvaSrivastava** [comment]
Apurva Srivastava- 151500123- Section 4A

**Comment by HarshitKhare** [comment]
Harshit Khare - 151500221 - Section 4A

**Comment by nikhil-web** [comment]
Nikhil Pandey - 151500322 - 4A

**Comment by Anubhav-Yadav** [comment]
Anubhav - 151500108 - Section 4C

**Comment by 05aashijain** [comment]
Aashi - 151500003 - Section 4D

**Comment by rshbhsngh62041** [comment]
Rishabh Singh - 151500417 - Section 4D

**Comment by akkii0001** [comment]
Akshay Chauhan - 151500055 - section 4C

**Comment by bates2525** [comment]
Piyush Sharma-151500341-Section 4A

**Comment by yadavpradeep-2024** [comment]
Pradeep Yadav- 151500345(B1)

**Comment by sarthakkatiyar** [comment]
Sarthak Katiyar - 151500451 - 4E

**Comment by Rahul-Gupt** [comment]
Rahul Gupta - 151500386 - Section 4E

**Comment by ArneshMaurya** [comment]
Arnesh Maurya - 1515001294

**Comment by immayu** [comment]
Mayank singh-151500286-4D

**Comment by ekansh22** [comment]
Ekansh Gupta - 151500197 - Section 4A

**Comment by gauravvs** [comment]
Gaurav Verma  161599002 section 4E

**Comment by tANUJsHARMA8** [comment]
Tanuj Sharma - 151500574 - Section 4D

**Comment by ssarikarajput** [comment]
Sarika Singh 
151500450
Section 4B

**Comment by VIJAYSVE** [comment]
Vijay Singh Verma 151500601 4D

**Comment by shubham701** [comment]
Shubham Kumar Yadav - 151500523 - Section 4E

**Comment by vikasjadon19** [comment]
Vikas jadon 4E 151500603

**Comment by piyushupa** [comment]
Piyush Kumar Upadhyay 151500339 sec-4D

**Comment by thebluntcoder** [comment]
Uttkarsh Mishra- 151500591 - Section 4B

**Comment by gulshan999** [comment]
Gulshan Kumar-151500213-4D

**Comment by shikhashrma** [comment]
Shikha Sharma-151500476-Sec 4B

**Comment by neelanshkumar** [comment]
Neelansh Kumar -151500314 - 4D

**Comment by Bladewalker007** [comment]
Himanshu Kumar Agrawal - 151500231 -4A

**Comment by ArneshMaurya** [comment]
Arnesh Maurya - 151500129 - 4A

**Comment by Shivanjaligupta** [comment]
Shivanjali gupta 151500508 B(47)

**Comment by BhavyaRajSharma** [comment]
Bhavya Raj Sharma - 151500162 - 4C

**Comment by shivamdwivedi586** [comment]
Shivam Dwivedi-151500485-sec-4E

**Comment by dbc2201** [comment]
Anuj Gupta - 151500112 - 4E

**Comment by Shivanjaligupta** [comment]
Anamika Singh 151500087 A(22)
Sagar Agrawal 151500434 D(49)

**Comment by AnshulGoyal04** [comment]
Anshul Goyal - 151500105 - Section 4D

**Comment by DRAGONKINGEMPEROR** [comment]
Abhishek Gautam - 151500017 - Section 4A
